force-app/main/default/objects/Account/fields/Customer_Lifetime_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lifetime_Value__c</fullName>
    <label>Customer Lifetime Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Name</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CalculateParentCLV_Test.cls
@isTest
public class CalculateParentCLV_Test {

    @isTest
    static void testCalculateCLV() {
        
        Account parentAcc = new Account(
            Name = 'Parenr Account',
            Customer_Lifetime_Value__c = 100
        );
        insert parentAcc;
        
        
        Account childAcc = new Account(
            Name = 'Test Account',
            ParentId  = parentAcc.Id,
            Customer_Lifetime_Value__c = 100
        );
        insert childAcc;
        
        
        
        Opportunity__c opp = new Opportunity__c(
            Name = 'Test Privated limites',
            Account_Name__c  = childAcc.Id,
            Amount__c = 40000
        );
        
        insert opp;

        
        CalculateParentCLV.FlowInput input = new CalculateParentCLV.FlowInput();
        input.accountId = childAcc.Id;
        input.childTotalCLV = 50;

        List<CalculateParentCLV.FlowInput> inputList = new List<CalculateParentCLV.FlowInput>();
        inputList.add(input);

        Test.startTest();
        CalculateParentCLV.flowDataForCLV(inputList);
        Test.stopTest();

        
        Account updatedAcc = [
            SELECT Customer_Lifetime_Value__c
            FROM Account
            WHERE Id = :childAcc.Id
        ];

        System.assertEquals(150, updatedAcc.Customer_Lifetime_Value__c);
    }
}